import { randomBytes } from 'node:crypto';
import { Router } from 'express';
import { z } from 'zod';
import { prisma } from '../config/database.js';
import { environment } from '../config/environment.js';
import { AppError } from '../errors/app-error.js';
import { encrypt } from '../integrations/slack/slack-service.js';

export const slackRouter = Router();
const requireConfig = () => { if (!environment.SLACK_CLIENT_ID || !environment.SLACK_CLIENT_SECRET || !environment.SLACK_REDIRECT_URI) throw new AppError(503, 'SLACK_NOT_CONFIGURED', 'Slack OAuth is not configured.'); };
slackRouter.get('/connect', (request, response, next) => { try { requireConfig(); const state = randomBytes(24).toString('hex'); request.session.oauthState = state; const params = new URLSearchParams({ client_id: environment.SLACK_CLIENT_ID!, redirect_uri: environment.SLACK_REDIRECT_URI!, state, scope: 'chat:write' }); response.redirect(`https://slack.com/oauth/v2/authorize?${params}`); } catch (error) { next(error); } });
slackRouter.get('/callback', async (request, response, next) => { try { requireConfig(); const { code, state } = z.object({ code: z.string(), state: z.string() }).parse(request.query); if (!request.session.userId || state !== request.session.oauthState) throw new AppError(400, 'INVALID_OAUTH_STATE', 'Invalid Slack OAuth state.'); const form = new URLSearchParams({ code, client_id: environment.SLACK_CLIENT_ID!, client_secret: environment.SLACK_CLIENT_SECRET!, redirect_uri: environment.SLACK_REDIRECT_URI! }); const result = await fetch('https://slack.com/api/oauth.v2.access', { method: 'POST', body: form }); const data = await result.json() as { ok: boolean; access_token?: string; team?: { id: string; name: string }; error?: string }; if (!data.ok || !data.access_token || !data.team) throw new AppError(502, 'SLACK_OAUTH_FAILED', data.error ?? 'Slack authorization failed.'); await prisma.slackConnection.upsert({ where: { userId: request.session.userId }, update: { workspaceId: data.team.id, workspaceName: data.team.name, accessTokenEncrypted: encrypt(data.access_token) }, create: { userId: request.session.userId, workspaceId: data.team.id, workspaceName: data.team.name, accessTokenEncrypted: encrypt(data.access_token) } }); delete request.session.oauthState; response.redirect(environment.FRONTEND_URL); } catch (error) { next(error); } });
slackRouter.get('/status', async (request, response, next) => { try { if (!request.session.userId) throw new AppError(401, 'UNAUTHENTICATED', 'Authentication required.'); const connection = await prisma.slackConnection.findUnique({ where: { userId: request.session.userId }, select: { workspaceName: true, channelId: true } }); response.json({ connected: Boolean(connection), connection }); } catch (error) { next(error); } });
slackRouter.post('/disconnect', async (request, response, next) => { try { if (!request.session.userId) throw new AppError(401, 'UNAUTHENTICATED', 'Authentication required.'); await prisma.slackConnection.deleteMany({ where: { userId: request.session.userId } }); response.status(204).send(); } catch (error) { next(error); } });
